In [ ]:
%pip install google-cloud-bigquery-storage pyarrow

In [1]:
from google.cloud import storage
import os
os.environ["GOOGLE_CLOUD_PROJECT"] = "yellow-taxi-trips-2026"

In [2]:
# On charge l'extension BigQuery pour le notebook
%load_ext google.cloud.bigquery

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\__init__.py:239: FutureWarning: %load_ext google.cloud.bigquery is deprecated. Install bigquery-magics package and use `%load_ext bigquery_magics`, instead.
  warnings.warn(

-- Training with BOOSTED TREE REGRESSOR

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL `yellow-taxi-trips-2026.ml_dataset.boosted_tree_regressor`
  OPTIONS (model_type="BOOSTED_TREE_REGRESSOR", enable_global_explain=TRUE, input_label_cols=["total_amount"])
AS 
SELECT * FROM `yellow-taxi-trips-2026.ml_dataset.preprocessed_train_data`;

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\job\query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [5]:
%%bigquery
SELECT COUNT(*) FROM `yellow-taxi-trips-2026.ml_dataset.preprocessed_test_data`;

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\job\query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\table.py:2714: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

     f0_
0  75000

-- Evaluate the trained model with the test data

In [4]:
%%bigquery
SELECT * FROM 
ML.EVALUATE(MODEL `yellow-taxi-trips-2026.ml_dataset.boosted_tree_regressor`, 
(SELECT * FROM `yellow-taxi-trips-2026.ml_dataset.preprocessed_test_data`));

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\job\query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\table.py:2714: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

,mean_absolute_error,mean_squared_error,mean_squared_log_error,median_absolute_error,r2_score,explained_variance
0,0.804264,1.524049,0.006086,0.548241,0.906804,0.90745

-- Example for making predictions from the model

In [8]:
%%bigquery
SELECT * FROM
ML.PREDICT (MODEL `yellow-taxi-trips-2026.ml_dataset.boosted_tree_regressor`, 
(SELECT * FROM `yellow-taxi-trips-2026.ml_dataset.preprocessed_test_data`));

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\job\query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\table.py:2714: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

,predicted_total_amount,PULocationID,DOLocationID,passenger_count,trip_distance,trip_duration,pickup_dayofweek,pickup_month,pickup_year,pickup_hour,is_weekend,is_credit_card,total_amount
0,8.830137,41,166,1.0,1.10,4.383333,2,11,2024,7,0,0,1.00
1,14.137486,260,93,1.0,10.29,79.700000,1,11,2024,22,0,0,1.01
2,8.337940,79,113,1.0,0.50,5.066667,2,11,2024,22,0,0,1.01
3,11.534009,262,74,1.0,1.30,5.183333,5,11,2024,0,1,0,1.01
4,14.582946,132,10,1.0,3.02,7.366667,3,11,2024,20,0,0,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74995,29.170916,114,170,3.0,2.58,28.183333,5,11,2024,19,1,1,33.60
74996,28.933121,238,68,1.0,3.52,25.016667,5,11,2024,14,1,1,33.60
74997,28.864450,211,164,2.0,2.21,29.416667,5,11,2024,18,1,1,33.60
74998,27.007278,166,48,1.0,3.46,23.383333,5,11,2024,19,1,1,33.60
74999,27.855013,234,43,1.0,2.13,27.283333,5,11,2024,14,1,1,33.60

-- Query the model's global explanations

In [9]:
%%bigquery
SELECT * FROM ML.GLOBAL_EXPLAIN(MODEL `yellow-taxi-trips-2026.ml_dataset.boosted_tree_regressor`);

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\job\query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\table.py:2714: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

             feature  attribution
0      trip_duration     2.466042
1     is_credit_card     0.773357
2      trip_distance     0.718838
3       PULocationID     0.088890
4       DOLocationID     0.081189
5        pickup_hour     0.009040
6    passenger_count     0.002499
7   pickup_dayofweek     0.001007
8       pickup_month     0.000000
9        pickup_year     0.000000
10        is_weekend     0.000000

-- Training with RANDOM FOREST REGRESSOR

In [6]:
%%bigquery
CREATE OR REPLACE MODEL `yellow-taxi-trips-2026.ml_dataset.rf_model`
  OPTIONS (model_type="RANDOM_FOREST_REGRESSOR", enable_global_explain=TRUE, input_label_cols=["total_amount"])
AS 

SELECT * FROM `yellow-taxi-trips-2026.ml_dataset.preprocessed_train_data`

c:\Users\EDITH ADJE\Documents\GCP Project\NYC_Taxi_GCP\projet_data_taxi_complet\nyc-yellow-taxi-trips\.venvreport\Lib\site-packages\google\cloud\bigquery\job\query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%bigquery
SELECT * FROM 
ML.EVALUATE(MODEL `yellow-taxi-trips-2026.ml_dataset.yellow_trips_rf`, 
(SELECT * FROM `yellow-taxi-trips-2026.ml_dataset.preprocessed_test_data`));